Cme feature/target button full
mff-uk/dataspecer pull request #802
Opened 2024-11-18 00:04 UTC by RadStr

2024-12-02 07:13 UTC, skodapetr requested changes
Just two minors, before merge.

2024-12-02 07:13 UTC, skodapetr commented on applications/conceptual-model-editor/src/action/center-viewport-to-visual-entity.ts
> +// TODO: Falls apart if we want to represent 1 semantic entities by more visual ones, in such case we want to pass in identifiers of both semantic and the visual entity.
Move this to an issue. I do not see how this should be resolved localy.

2024-12-02 07:13 UTC, skodapetr commented on applications/conceptual-model-editor/src/diagram/diagram-controller.ts
> +      console.log("Diagram.fitToView", { identifiers });
Do we need this log here? Seems like it was used for debug during development of  a particular feature, perhaps not needed anymore?

2024-12-02 10:26 UTC, RadStr commented
Should be fine now - Removed the two lines.

On a side note, I noticed two things in the main branch:

1. Layouting doesn't work - When you were rewriting part of code you wrote if instead of else if, but that is fixed in another branch, for which I will open PR next.
2. The target button no longer works, but maybe that will be fixed by this merge

2024-12-03 06:45 UTC, skodapetr commented on applications/conceptual-model-editor/src/action/center-viewport-to-visual-entity.ts
> +// TODO: Falls apart if we want to represent 1 semantic entities by more visual ones, in such case we want to pass in identifiers of both semantic and the visual entity.
Both, I would like to have this as an issues, as we plan to identify entities using model identifier and entity identifier.

2024-12-03 06:50 UTC, skodapetr commented
We can merge once the conflict is resolved.

2024-12-03 13:20 UTC, merged

2024-12-03 13:21 UTC, skodapetr commented
Yet, it would be best to have a way how to enforce the right match, model to model, entity to entity, in TS. Perhaps we can introduce a new type to wrap both of them together as  a way to reference an entity. We can discuss this in the issue.

2024-12-03 13:47 UTC, RadStr commented
> Yet, it would be best to have a way how to enforce the right match, model to model, entity to entity, in TS. Perhaps we can introduce a new type to wrap both of them together as a way to reference an entity. We can discuss this in the issue.

I am not sure if we are thinking about the same issue, but I know what you mean. We can quickly discuss that tomorrow if there will be time.